name: telco
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py39h2804cbe_1
  - argon2-cffi=21.1.0=py39h5161555_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd8ed1ab_0
  - bottleneck=1.3.2=py39heec5a64_1
  - ca-certificates=2021.10.8=h4653dfc_0
  - certifi=2021.10.8=py39h2804cbe_0
  - cffi=1.15.0=py39h22df2f2_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.4=hc377ac9_0
  - imbalanced-learn=0.9.0=pyhd8ed1ab_0
  - importlib-metadata=3.3.0=pyhd8ed1ab_1
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=5.5.5=py39h32adebf_0
  - ipython=7.31.1=py39hca03da5_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=py39hca03da5_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=0.17.0=py_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hca03da5_0
  - libcxx=12.0.0=hf6beb65_1
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0=11_1_0_h6a59814_26
  - libgfortran5=11.1.0=h6a59814_26
  - libiconv=1.16=h1a28f6b_1
  - libopenblas=0.3.17=hea475bc_1
  - libsodium=1.0.18=h27ca646_1
  - llvm-openmp=12.0.0=haf9daa7_1
  - markupsafe=2.0.1=py39h1a28f6b_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39h5161555_1004
  - nbconvert=5.6.1=pyhd8ed1ab_2
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h1a28f6b_2
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - notebook=6.4.8=pyha770c72_0
  - numexpr=2.8.1=py39h144ceef_0
  - numpy=1.21.2=py39hb38b75b_0
  - numpy-base=1.21.2=py39h6269429_0
  - openssl=1.1.1l=h3422bc3_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py39hc377ac9_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=py39hca03da5_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py39h1a28f6b_0
  - python=3.9.7=hc70090a_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2020.1=py_0
  - pyzmq=22.3.0=py39h02c6a76_0
  - readline=8.1.2=h1a28f6b_1
  - scikit-learn=1.0.2=py39h9197a36_1
  - scipy=1.7.3=py39h2f0f56f_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py39hca03da5_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.2=h1058600_0
  - terminado=0.13.1=py39hca03da5_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.11=hb8d0fd4_0
  - tornado=6.1=py39h5161555_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h1a28f6b_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h5a0b063_4
  - pip:
    - pillow==9.0.1
    - torch==1.10.2
    - torchaudio==0.10.2
    - torchvision==0.11.3
prefix: /Users/sfdev/miniconda3/envs/telco
